version: "3.3"

volumes:
  mongodb:
  data:

networks:
  kowalski:

services:

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
#    entrypoint: python -m pytest -s test_api.py
    image: dmitryduev/kowalski_api:latest
    volumes:
      - data:/data
    expose:
      - "4000"
    # fixme:
    ports:
      - "4000:4000"
    links:
      - mongo:kowalski-mongo
    restart: always
    depends_on:
      - mongo
    networks:
      - kowalski

  ingester:
    build:
      context: .
      dockerfile: ingester.Dockerfile
#    entrypoint: supervisord -n -c supervisord_ingester.conf
#    entrypoint: python -m pytest -s test_ingester.py
    image: dmitryduev/kowalski_ingester:latest
    volumes:
      - data:/data
    links:
      - mongo:kowalski-mongo
    restart: always
    depends_on:
      - mongo
    networks:
      - kowalski

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    # fixme:
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadminsecret
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
      - kowalski