version: '3.3'

services:

  kafka:
    build:
      context: .
      dockerfile: kafka-producer.Dockerfile
    volumes:
      - ./data:/data
    expose:
      - "9092"
    ports:
      - "9092:9092"
    restart: always
